# Generated by Django 3.2.19 on 2023-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, upload_to='images/%Y-%m-%d')),
                ('image2', models.ImageField(blank=True, upload_to='images/%Y-%m-%d')),
                ('image3', models.ImageField(blank=True, upload_to='images/%Y-%m-%d')),
                ('image4', models.ImageField(blank=True, upload_to='images/%Y-%m-%d')),
                ('image5', models.ImageField(blank=True, upload_to='images/%Y-%m-%d')),
                ('image6', models.ImageField(blank=True, upload_to='images/%Y-%m-%d')),
                ('product_name', models.CharField(max_length=50)),
                ('product_brand', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=200)),
                ('product_items_available', models.CharField(max_length=50)),
            ],
        ),
    ]
