# Generated by Django 3.2.19 on 2023-05-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_items_available',
            new_name='product_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
